siguel:	Cidade.o Quadra.o Semaforo.o Hidrante.o Torre.o Circulo.o Retangulo.o Lista.o siguel.o ArqSvg.o ArqQry.o Operacoes.o Vetor.o Pilha.o QuadTree.o EnvoltorioConvexo.o Quicksort.o Calculos.o Hash.o Pessoa.o Dicionario.o Grafo.o ArqPm.o ArqTm.o ArqEc.o Procedimentos.o EstabelecimentoComercial.o ArqVia.o Rota.o
	gcc -o siguel siguel.o Cidade.o Quadra.o Semaforo.o Hidrante.o Torre.o Circulo.o Retangulo.o Lista.o ArqSvg.o ArqQry.o Operacoes.o Vetor.o Pilha.o QuadTree.o EnvoltorioConvexo.o Quicksort.o Calculos.o Hash.o Pessoa.o Dicionario.o Grafo.o ArqPm.o ArqTm.o ArqEc.o Procedimentos.o EstabelecimentoComercial.o ArqVia.o Rota.o -lm

siguel.o: siguel.c
	gcc -o siguel.o -c siguel.c -g -pedantic -ansi

Lista.o: Lista.c
	gcc -o Lista.o -c Lista.c -g -pedantic -ansi

Quadra.o: Quadra.c
	gcc -o Quadra.o -c Quadra.c -g -pedantic -ansi

Semaforo.o: Semaforo.c
	gcc -o Semaforo.o -c Semaforo.c -g -pedantic -ansi

Hidrante.o: Hidrante.c
	gcc -o Hidrante.o -c Hidrante.c -g -pedantic -ansi

Torre.o: Torre.c
	gcc -o Torre.o -c Torre.c -g -pedantic -ansi

Circulo.o: Circulo.c
	gcc -o Circulo.o -c Circulo.c -g -pedantic -ansi

Retangulo.o: Retangulo.c
	gcc -o Retangulo.o -c Retangulo.c -g -pedantic -ansi

Cidade.o: Cidade.c
	gcc -o Cidade.o -c Cidade.c	-g -pedantic -ansi

ArqSvg.o:	ArqSvg.c
	gcc -o ArqSvg.o -c ArqSvg.c -g -pedantic -ansi

ArqQry.o:	ArqQry.c
	gcc -o ArqQry.o -c ArqQry.c -g -pedantic -ansi

Operacoes.o: Operacoes.c
	gcc -o Operacoes.o -c Operacoes.c -g -pedantic -ansi

Vetor.o: Vetor.c
	gcc -o Vetor.o -c Vetor.c -g -pedantic -ansi

Pilha.o: Pilha.c
	gcc -o Pilha.o -c Pilha.c -g -pedantic -ansi

QuadTree.o:	QuadTree.c
	gcc -o QuadTree.o -c QuadTree.c -g -pedantic -ansi

EnvoltorioConvexo.o: EnvoltorioConvexo.c
	gcc -o EnvoltorioConvexo.o -c EnvoltorioConvexo.c -g -pedantic -ansi

Quicksort.o: Quicksort.c
	gcc -o Quicksort.o -c Quicksort.c -g -pedantic -ansi

Calculos.o: Calculos.c
	gcc -o Calculos.o -c Calculos.c -g -pedantic -ansi

Hash.o: Hash.c
	gcc -o Hash.o -c Hash.c -g -pedantic -ansi

Pessoa.o: Pessoa.c
	gcc -o Pessoa.o -c Pessoa.c -g -pedantic -ansi

Dicionario.o: Dicionario.c
	gcc -o Dicionario.o -c Dicionario.c -pedantic -ansi

Grafo.o: Grafo.c
	gcc -o Grafo.o -c Grafo.c -pedantic -ansi

ArqPm.o: ArqPm.c
	gcc -o ArqPm.o -c ArqPm.c -pedantic -ansi

ArqTm.o: ArqTm.c
	gcc -o ArqTm.o -c ArqTm.c -pedantic -ansi

ArqEc.o: ArqEc.c
	gcc -o ArqEc.o -c ArqEc.c -pedantic -ansi

ArqVia.o: ArqVia.c
	gcc -o ArqVia.o -c ArqVia.c -pedantic -ansi

Procedimentos.o: Procedimentos.c
	gcc -o Procedimentos.o -c Procedimentos.c -pedantic -ansi

EstabelecimentoComercial.o: EstabelecimentoComercial.c
	gcc -o EstabelecimentoComercial.o -c EstabelecimentoComercial.c -pedantic -ansi

Rota.o: Rota.c
	gcc -o Rota.o -c Rota.c -pedantic -ansi

clean:
	rm -rf *.o vgcore* siguel
